always_for_in = true
whitespace_in_kwargs = false
whitespace_typedefs = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = true
format_docstrings = true
conditional_to_if = true
annotate_untyped_fields_with_any = false
trailing_comma = false