name = "IfTraits"
uuid = "7a6924a7-8ee3-403d-a531-72325acf0e39"
authors = ["Johannes Nägele <johannes-naegele@web.de>"]
version = "0.1.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
